### ISSUE TITLE
HTTP challenges can't be performed on wildcard domains.

### ISSUE THREAD

**Issue by Ta2Ta2** [mlocati/concrete5_acme#1]
Hello,

while adding wildcard domain, I get this error and there was no option to change the preferred challenges to DNS.

Please note I'm using cloudflare on the domain I'm trying to add.

**Comment by mlocati** [comment]
The problem is that DNS challenges require APIs to configure the DNS Server, and those APIs are strictly tied to every provider.

At the moment I haven't implemented any driver for DNS Challenges (except the test one which uses challtestsrv - which can be used as a template).

So, what about writing this driver yourself? This is an open source project, after all;)

**Comment by Ta2Ta2** [comment]
Thanks for your prompt response! 

sure thing
